In [9]:
import numpy as np
a1 = np.arange(10)
print(a1[1])
print(a1[4:6])
print(a1[::2])
print(a1[-1])



1
[4 5]
[0 2 4 6 8]
9


In [12]:
a2 = np.random.randint(0,10,(5,5))
print(a2)
print(a2[[0,3,4],[1,3,4]])

[[0 2 3 6 0]
 [6 8 9 8 6]
 [5 9 0 7 3]
 [5 3 1 1 1]
 [0 2 8 4 3]]
[2 1 3]


In [5]:
a2[1] = 0
a2[1] = np.array([1,2,3,4,5])
a2 = np.where(a2<5,0,1)
# a2[a2<5] = 0
print(a2)

[[1 1 1 1 0]
 [0 0 0 0 1]
 [1 0 0 1 1]
 [0 1 1 1 0]
 [0 1 0 1 0]]


In [9]:
b1 = np.random.randint(0,10,(8,1,4))
print(b1)
print("-"*50)
b2 = np.random.randint(0,10,(8,4,50))
print(b2)
print("-"*50)
print(b1+b2)
b3 = b1+b2
print(b3.shape)


[[[0 5 4 2]]

 [[6 4 4 7]]

 [[4 7 2 3]]

 [[0 0 7 5]]

 [[7 0 8 8]]

 [[8 4 1 3]]

 [[6 6 9 1]]

 [[9 0 2 9]]]
--------------------------------------------------
[[[1 7 0 ... 4 5 4]
  [7 4 7 ... 6 4 8]
  [9 9 4 ... 7 2 5]
  [2 0 7 ... 3 1 0]]

 [[2 4 7 ... 0 9 0]
  [6 1 8 ... 1 7 6]
  [1 9 2 ... 3 4 3]
  [7 7 5 ... 5 8 3]]

 [[3 0 0 ... 6 5 1]
  [6 4 0 ... 3 8 1]
  [3 1 4 ... 1 7 2]
  [4 0 7 ... 5 3 7]]

 ...

 [[0 4 1 ... 2 9 8]
  [5 7 0 ... 4 5 8]
  [8 6 9 ... 5 3 0]
  [8 3 8 ... 7 6 0]]

 [[9 6 1 ... 8 9 5]
  [3 9 2 ... 2 1 6]
  [5 2 4 ... 5 1 1]
  [9 2 9 ... 6 6 2]]

 [[9 6 8 ... 9 7 5]
  [6 9 0 ... 3 8 5]
  [3 7 5 ... 0 3 6]
  [1 1 5 ... 2 5 6]]]
--------------------------------------------------


ValueError: operands could not be broadcast together with shapes (8,1,4) (8,4,50) 

In [2]:
a = np.random.randint(0,100,(20,2))
print(a)

[[17 21]
 [72 63]
 [85  2]
 [90 48]
 [96 52]
 [35 35]
 [79 61]
 [95 36]
 [63 60]
 [96 82]
 [37 89]
 [54 89]
 [80 74]
 [12 21]
 [94 81]
 [47 55]
 [91 24]
 [51 26]
 [61 40]
 [91 94]]


In [ ]:
np.savetxt('score.csv',)

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.DataFrame(np.arange(12).reshape(3,4),index=['a','b','c'],columns=['A','B','C','D'])
print(a)

   A  B   C   D
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11


In [7]:
a.loc['a':'b','A']

a    0
b    4
Name: A, dtype: int64

In [23]:
df = pd.DataFrame([['A公司',  1,  2,  3,  4,  5], ['B公司', 0, 0, 1, 0, 0], ['C公司', 2, 3, 4, 5, 0]], columns=['公司名','北京','江苏','浙江','上海','广东'], index=None)
df.to_csv('df1.csv')
df1 = pd.read_csv('df1.csv')
print(df1)
# df_sum = df.sum()   # 全部列求和
df_sum = df[['北京', '江苏', '浙江', '上海', '广东']].sum()  # 指定列求和，默认是每列求和
df.loc[df.index.max()+1] = df_sum
df.loc[df.index.max(),'公司名'] = '各省合计'
print(df)


   Unnamed: 0  公司名  北京  江苏  浙江  上海  广东
0           0  A公司   1   2   3   4   5
1           1  B公司   0   0   1   0   0
2           2  C公司   2   3   4   5   0
    公司名   北京   江苏   浙江   上海   广东
0   A公司  1.0  2.0  3.0  4.0  5.0
1   B公司  0.0  0.0  1.0  0.0  0.0
2   C公司  2.0  3.0  4.0  5.0  0.0
3  各省合计  3.0  5.0  8.0  9.0  5.0
