In [32]:
import torch
import numpy as np

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.2150, 0.2954, 0.0610],
        [0.3715, 0.3824, 0.9586],
        [0.0303, 0.7815, 0.9637],
        [0.3337, 0.1852, 0.6072],
        [0.8319, 0.5626, 0.7121]])


In [7]:
x = torch.zeros(5,3).long()
x.dtype

torch.int64

In [8]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [10]:
#尽量重用原来的信息
x = x.new_ones(5,3)


x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
#产生和x相同形状的tensor
torch.randn_like(x,dtype=torch.float)


tensor([[ 1.1093,  0.1431, -1.5540],
        [-2.0540, -0.4554,  0.9733],
        [-1.7270,  0.4171, -1.2780],
        [ 0.9151, -0.9445, -0.5391],
        [ 0.8932,  0.8594,  1.8729]])

In [12]:
x.shape

torch.Size([5, 3])

In [13]:
x.dtype


torch.float64

In [16]:
y = torch.rand(5,3)
y.dtype

torch.float32

In [15]:
x+y

tensor([[1.9257, 1.0002, 1.2411],
        [1.8874, 1.3411, 1.0615],
        [1.8913, 1.4436, 1.5134],
        [1.9445, 1.0666, 1.5708],
        [1.5219, 1.9884, 1.5477]], dtype=torch.float64)

In [17]:
torch.add(x,y)

tensor([[1.4071, 1.7009, 1.1523],
        [1.0900, 1.8854, 1.0499],
        [1.8618, 1.3076, 1.2554],
        [1.5448, 1.8703, 1.2977],
        [1.9436, 1.5053, 1.2152]], dtype=torch.float64)

In [19]:
#in-place运算 把计算的值负值给y

y.add_(x)
y

tensor([[2.4071, 2.7009, 2.1523],
        [2.0900, 2.8854, 2.0499],
        [2.8618, 2.3076, 2.2554],
        [2.5448, 2.8703, 2.2977],
        [2.9436, 2.5053, 2.2152]])

In [20]:

x[:,1:]

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [23]:
#resize
x = torch.randn(4,4)
# y = x.reshape(16)
y = x.view(-1,8)
y

tensor([[-0.2918, -0.4779, -1.0772, -0.9575,  2.5216, -0.2173,  0.8928, -0.3119],
        [ 0.2942, -0.8621,  0.0733,  1.6780, -1.2808, -0.2707,  0.3071, -0.0518]])

In [29]:
x = torch.randn(1,dtype=torch.float)
x

tensor([0.2654])

In [30]:
x.data
x.grad
x.item()

0.26539796590805054

In [31]:
a = torch.ones(5)
b = a.numpy()
#a和b共享内存空间
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)#out=a直接在原内存数据上运算
print(a)

[2. 2. 2. 2. 2.]


In [34]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [35]:
a = a+1#a=a+1是重新开辟一块内存空间赋值给a 
a

array([3., 3., 3., 3., 3.])

In [36]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [38]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu',torch.double))
    
    

In [39]:
torch.cuda.is_available()

False

In [41]:
y.to('cpu').data.numpy()
y.cpu().data.numpy()


array([[-0.2917906 , -0.47787067, -1.077227  , -0.9574687 ,  2.5215757 ,
        -0.2173205 ,  0.89277095, -0.31188238],
       [ 0.29415348, -0.86206275,  0.07327577,  1.678049  , -1.2807901 ,
        -0.2707111 ,  0.30713564, -0.05183601]], dtype=float32)

# numpy实现两层神经网络
- $h = W_1x+b_1$
- $a = max(0,h)$
- $y_{hat} = W_2a + b_2$

- forward pass
- loss
- backward pass

In [43]:
N = 64 #64个输入
D_in = 1000 #输入是1000维的
H = 100 #隐藏层100维
D_out = 10 #输出是10维的
x = np.random.randn(N,D_in)
y = np.random.randn(N,D_out)

w1 = np.random.randn(D_in,H)
w2 = np.random.randn(H,D_out)
learning_rate = 1e-6
for t in range(500):
    # forward pass
    h = x.dot(w1)
    h_relu = np.maximum(h,0)
    y_pred = h_relu.dot(w2)
    #compute loss
    loss = np.square(y_pred - y).sum()
    print(t,loss)
    
    #backward pass
    #compute the gradient
    #update weights of w1 and w2
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    #update weights 
    w1 -= learning_rate*grad_w1
    w2 -= learning_rate*grad_w2
    
    
    



0 34210439.04437022
1 29548326.536118295
2 28432525.14037171
3 26016708.231640372
4 20691880.91926273
5 14087122.66745343
6 8445452.563862741
7 4828112.502337539
8 2828370.317144651
9 1792347.1220392645
10 1244205.3090377848
11 934433.240870096
12 742070.2673502418
13 611279.170521785
14 514901.71056293935
15 439882.2415619083
16 379372.0845376621
17 329409.9203727744
18 288119.52294012834
19 253182.67112728133
20 223394.14406846697
21 197798.45125539327
22 175715.50673178985
23 156559.1725402293
24 139861.16482738237
25 125256.0271516064
26 112434.35004804144
27 101146.81650765691
28 91181.91582307212
29 82356.87156547766
30 74534.72860953631
31 67568.93534816893
32 61361.651811395335
33 55808.961110278135
34 50828.4517991249
35 46353.41152593722
36 42325.74264441503
37 38692.99614153681
38 35422.18810602847
39 32466.899877537384
40 29788.668541370924
41 27357.315994271747
42 25146.376955668387
43 23133.78448031428
44 21299.59724175204
45 19628.62810693402
46 18101.96433714904
47 1670

415 7.82224205230282e-06
416 7.415132844774259e-06
417 7.029320202015491e-06
418 6.663680525164294e-06
419 6.317188794224768e-06
420 5.988847951769389e-06
421 5.6775679942149204e-06
422 5.38266541149702e-06
423 5.103036936793027e-06
424 4.83798930720786e-06
425 4.586778158815414e-06
426 4.348668789668956e-06
427 4.122964690568939e-06
428 3.909030475225394e-06
429 3.7062545369094053e-06
430 3.5140731547187144e-06
431 3.3318748232438808e-06
432 3.1591683303031873e-06
433 2.9954619671079426e-06
434 2.840283974830828e-06
435 2.693204845805671e-06
436 2.553788050319308e-06
437 2.421598815480276e-06
438 2.2962920684842517e-06
439 2.1774940703760155e-06
440 2.064873349304821e-06
441 1.9580969455387957e-06
442 1.8568754609820503e-06
443 1.7609111135190761e-06
444 1.669927196335473e-06
445 1.5836675265797486e-06
446 1.5018985635681846e-06
447 1.4243622896470357e-06
448 1.350862967051145e-06
449 1.2811853807882379e-06
450 1.215103163267519e-06
451 1.1524439570587446e-06
452 1.0930364450781366e-0

In [47]:
y

array([[ 0.93659703,  0.9423386 , -0.92959357,  0.13372073,  1.01177194,
        -0.51732471, -1.7015934 , -0.47939438, -0.29767887,  0.66085314],
       [ 0.53833051, -1.58602142, -0.09764107, -0.41984048,  1.60053027,
         1.55280754,  2.10691   ,  1.12103169, -2.5207701 , -0.21174282],
       [-0.01857023, -0.58288327, -1.24946987, -0.54699679, -1.01033824,
         1.74235781, -1.2603357 ,  1.17880548,  2.79585217,  0.96427802],
       [ 0.67665955,  1.0138347 , -1.26686392,  1.31479244, -0.84775961,
         0.76617653, -0.3505288 , -0.73979483,  1.61075256,  0.15430913],
       [ 0.44746698, -0.95215565,  0.97839066, -1.39363429,  1.63569767,
        -0.9692346 , -0.81216154, -0.11704154, -1.65780396, -1.5756187 ],
       [ 0.34364434,  0.16968555, -0.14064125, -0.72543023,  0.60340571,
        -1.25506621,  0.41720416,  0.47432813,  0.17878414, -1.61263763],
       [-0.22698752, -1.21234849, -0.15790377, -1.02245094, -0.75201856,
         0.8106572 ,  1.6941512 , -1.42854329

In [46]:
h = x.dot(w1)
h_relu = np.maximum(h,0)
y_pred = h_relu.dot(w2)

In [48]:
y_pred - y

array([[-4.24154079e-06, -6.36214005e-06,  3.70240916e-05,
         9.25120399e-06,  9.74289389e-06, -5.45842752e-06,
         1.27551551e-05, -1.12497616e-05,  2.82456976e-05,
        -1.04325275e-05],
       [-4.57621317e-06, -1.15666235e-06,  1.02363774e-05,
         4.59271995e-06,  1.10106177e-06,  9.33260807e-06,
        -1.35719099e-06, -4.69418411e-06,  6.58028066e-06,
        -9.42029683e-06],
       [ 1.02743585e-05, -2.81565268e-06, -8.38510947e-06,
        -1.18594950e-06, -2.47162347e-06, -1.10655779e-05,
        -1.18629846e-06,  1.52202783e-06, -1.13814133e-05,
         1.10128735e-05],
       [-5.77639235e-07, -4.22212203e-06,  1.31988295e-05,
         6.18274509e-06,  8.99606139e-06, -6.40513290e-07,
         4.91859718e-06, -6.43918274e-06,  2.10359236e-05,
        -1.10949124e-05],
       [ 2.60256295e-06, -3.30220942e-06,  1.06841284e-06,
        -5.84444764e-07,  2.18922740e-06,  1.53464652e-07,
        -5.68384561e-06,  8.76784839e-07,  1.54849324e-07,
         1.